# Generated by Django 5.1.4 on 2024-12-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joke_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomJoke',
        ),
    ]
