# Generated by Django 5.1.4 on 2025-01-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke_app', '0005_favouritejoke_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritejoke',
            name='joke',
            field=models.TextField(),
        ),
    ]
